from vector_store import add_documents

docs = [
    # --- TACTICS ---
    {"id": "t1", "text": "The high press is a defensive tactic where a team aggressively pressures the opponent high up the pitch immediately after losing the ball. The goal is to win the ball back quickly in dangerous areas. Teams like Liverpool under Klopp and Manchester City under Guardiola are known for this."},
    {"id": "t2", "text": "Gegenpressing, popularized by Jurgen Klopp at Borussia Dortmund and Liverpool, involves immediately pressing the opponent after losing possession. The idea is that the opposition is most vulnerable in the seconds after winning the ball before they organize."},
    {"id": "t3", "text": "Tiki-taka is a style of play pioneered by Barcelona and Spain, based on short passing, movement, and maintaining possession to create space. Key figures include Pep Guardiola, Xavi, Iniesta, and Busquets. It dominated European football from 2008 to 2013."},
    {"id": "t4", "text": "A low block is a defensive strategy where a team sits deep in their own half, compacting space and defending in two banks of four. Teams with less quality often use this against stronger opponents. It limits space but sacrifices attacking opportunities."},
    {"id": "t5", "text": "The 4-3-3 formation uses three forwards, three midfielders, and four defenders. It provides width through wingers, allows fullbacks to overlap, and gives midfield control with three central players. Used by Barcelona, Liverpool, and many top clubs."},
    {"id": "t6", "text": "The 4-2-3-1 formation uses a double pivot of two defensive midfielders protecting the back four, with an attacking midfielder behind a lone striker. It provides defensive solidity while allowing creative freedom to the number 10."},
    {"id": "t7", "text": "A false nine is a centre-forward who drops deep to receive the ball, dragging central defenders out of position and creating space for midfielders to run into. Lionel Messi famously played as a false nine under Guardiola at Barcelona."},
    {"id": "t8", "text": "Inverted wingers are wide players who play on the opposite side to their stronger foot — a right-footed player on the left wing and vice versa. This allows them to cut inside and shoot or create rather than cross from the byline. Robben, Salah, and Mane are classic examples."},
    {"id": "t9", "text": "A double pivot consists of two defensive midfielders sitting in front of the back four. Their roles include breaking up play, recycling possession, and providing cover when fullbacks attack. Busquets and Mascherano, or Fabinho and Henderson, are examples of successful double pivots."},
    {"id": "t10", "text": "Counter-attacking football involves absorbing pressure and hitting opponents on the break with pace and directness. Teams defend deep and transition quickly when they win the ball. Jose Mourinho's Inter Milan and Diego Simeone's Atletico Madrid are masters of this approach."},
    {"id": "t11", "text": "Pressing triggers are specific moments or situations that signal a team to press as a unit. Common triggers include a poor touch by the opponent, a back pass to the goalkeeper, or the ball going to a weaker-footed player. Coordinated pressing triggers make a press effective."},
    {"id": "t12", "text": "The 3-5-2 formation uses three centre-backs, two wingbacks who provide width, and two strikers supported by three central midfielders. It provides defensive solidity while allowing wingbacks to contribute offensively. Antonio Conte frequently uses this system."},
    {"id": "t13", "text": "Positional play, also known as juego de posicion, is a tactical approach where players occupy specific zones to create passing angles, overloads, and controlled possession. Pep Guardiola's teams are famous for using positional play to dominate space and move opponents out of shape."},
    {"id": "t14", "text": "A mid block is a defensive strategy where a team defends around the middle third of the pitch rather than pressing high or sitting very deep. It aims to stay compact, block central passing lanes, and force opponents wide."},
    {"id": "t15", "text": "Man-marking is a defensive approach where each player is assigned a specific opponent to follow closely. It can disrupt creative players but may create gaps if defenders are dragged out of position."},
    {"id": "t16", "text": "Zonal marking is a defensive system where players defend spaces rather than individual opponents. It is commonly used during open play and set pieces because it helps maintain team shape and compactness."},
    {"id": "t17", "text": "Overlapping fullbacks are defenders who run beyond the winger on the outside to create width and crossing opportunities. This tactic is common in teams that use inverted wingers who cut inside."},
    {"id": "t18", "text": "Underlapping runs occur when a fullback or midfielder runs inside the winger rather than around the outside. This can create dangerous central passing lanes and confuse defenders expecting a wide overlap."},
    {"id": "t19", "text": "A target man is a striker who uses physical strength, height, and aerial ability to hold up the ball and bring teammates into play. Traditional target men are useful for direct football and crossing systems."},
    {"id": "t20", "text": "A poacher is a striker who specializes in scoring from close range by anticipating rebounds, crosses, and loose balls. Poachers often make sharp movements inside the penalty box rather than dropping deep."},
    {"id": "t21", "text": "A box-to-box midfielder contributes both defensively and offensively, covering large distances across the pitch. They support attacks, press opponents, recover possession, and arrive late into the box to score."},
    {"id": "t22", "text": "A regista is a deep-lying playmaker who controls the tempo of the match from in front of the defense. Andrea Pirlo is one of the most famous examples of a regista."},
    {"id": "t23", "text": "A mezzala is a central midfielder who operates in the half-spaces, often drifting wide to support wingers and fullbacks. This role is common in three-man midfields."},
    {"id": "t24", "text": "Half-spaces are the vertical channels between the central area and the wide areas of the pitch. Creative players often exploit half-spaces because they offer better passing and shooting angles than the touchline."},
    {"id": "t25", "text": "A sweeper keeper is a goalkeeper who plays aggressively off their line to clear through balls and support the defense in possession. Manuel Neuer and Alisson Becker are famous examples."},
    {"id": "t26", "text": "Build-up play refers to how a team progresses the ball from defense into midfield and attack. Modern teams often use centre-backs, goalkeepers, and defensive midfielders to create passing triangles during build-up."},
    {"id": "t27", "text": "A back three system uses three central defenders and usually relies on wingbacks for width. It can provide defensive stability and create numerical superiority during build-up."},
    {"id": "t28", "text": "Wingbacks are wide players in a back three or back five system who must contribute both defensively and offensively. They provide width, crosses, recovery runs, and pressing support."},
    {"id": "t29", "text": "The 4-4-2 formation uses two banks of four and two strikers. It is simple, compact, and balanced, but can sometimes be outnumbered in central midfield against three-midfielder systems."},
    {"id": "t30", "text": "The 3-4-3 formation uses three centre-backs, two wingbacks, two central midfielders, and three attackers. It gives width through wingbacks and allows three forwards to press aggressively."},
    {"id": "t31", "text": "The 4-1-4-1 formation uses one defensive midfielder behind four midfielders and a lone striker. It provides midfield compactness and is useful for pressing while keeping defensive protection."},
    {"id": "t32", "text": "The 4-4-2 diamond formation uses four midfielders arranged narrowly with a defensive midfielder, two central midfielders, and an attacking midfielder. It gives central control but depends heavily on fullbacks for width."},
    {"id": "t33", "text": "Vertical football is a direct style of play focused on moving the ball forward quickly through progressive passes. It contrasts with slower possession football and is often used by teams that want fast transitions."},
    {"id": "t34", "text": "A tactical overload happens when a team places more players than the opponent in a specific area of the pitch. Overloads help create free players, passing options, and chances to progress the ball."},
    {"id": "t35", "text": "Switching play means moving the ball quickly from one side of the pitch to the other. This can exploit space when the defending team has shifted too far toward the ball side."},
    {"id": "t36", "text": "Rest defense refers to the defensive structure a team keeps while attacking. Good rest defense prevents counter-attacks by leaving enough players behind the ball in strong positions."},
    {"id": "t37", "text": "Counter-pressing is the immediate attempt to win the ball back after losing possession. It is effective because the opponent is often disorganized right after recovering the ball."},
    {"id": "t38", "text": "A tactical foul is a deliberate foul used to stop a dangerous counter-attack before it develops. Midfielders often commit tactical fouls to protect their team's defensive shape."},
    {"id": "t39", "text": "Parking the bus is an extreme defensive strategy where a team places many players near their own penalty area. It is used to protect a lead or frustrate a stronger opponent."},
    {"id": "t40", "text": "Set-piece routines are planned attacking moves from corners, free kicks, and throw-ins. Modern clubs use specialist coaches to design routines that create small advantages in crowded areas."},


    # --- PLAYERS ---
    {"id": "p1", "text": "Erling Haaland joined Manchester City in 2022 from Borussia Dortmund and broke the Premier League scoring record with 36 goals in his debut season. He is known for his pace, physicality, clinical finishing, and intelligent movement in behind defenses."},
    {"id": "p2", "text": "Mohamed Salah has been Liverpool's top scorer for multiple consecutive seasons. The Egyptian winger plays on the right but cuts inside onto his left foot. He is known for his pace, dribbling, and clinical finishing. He has scored over 200 goals for Liverpool."},
    {"id": "p3", "text": "Kevin De Bruyne is considered one of the best midfielders in the world. The Belgian plays for Manchester City and is known for his vision, passing range, long shots, and ability to control tempo. He has won multiple Premier League titles with City."},
    {"id": "p4", "text": "Harry Kane left Tottenham Hotspur in 2023 to join Bayern Munich. He was Tottenham's all-time top scorer and England's record goalscorer. Kane is known for his movement, link-up play, and ability to score and create goals."},
    {"id": "p5", "text": "Virgil van Dijk transformed Liverpool's defense after joining in January 2018 for a then-record fee for a defender. The Dutch centre-back is known for his aerial ability, composure on the ball, and commanding defensive presence."},
    {"id": "p6", "text": "Bukayo Saka is Arsenal's key player on the right wing. The young Englishman is known for his directness, creativity, and ability to score and assist. He has been Arsenal's most important player under Mikel Arteta and is a key figure for England."},
    {"id": "p7", "text": "Phil Foden is Manchester City's homegrown talent who has developed into one of England's best players. He can play as a winger, attacking midfielder, or false nine. He is known for his technical ability, vision, and intelligent movement."},
    {"id": "p8", "text": "Rodri is Manchester City's defensive midfielder and won the Ballon d'Or in 2024. The Spanish international is known for his positioning, passing, and ability to control the tempo of games. He is the engine of Guardiola's system."},
    {"id": "p9", "text": "Martin Odegaard is Arsenal's captain and creative hub. The Norwegian attacking midfielder is known for his technical ability, pressing work rate, and ability to find pockets of space. He has been crucial to Arsenal's title challenges."},
    {"id": "p10", "text": "Alisson Becker is Liverpool's Brazilian goalkeeper, considered one of the best in the world. Known for his shot-stopping, distribution, and composure. His arrival at Liverpool alongside Van Dijk transformed them into Premier League and Champions League winners."},
    {"id": "p11", "text": "Jude Bellingham became one of the most complete young midfielders in world football after moving from Borussia Dortmund to Real Madrid. He is known for ball carrying, pressing, leadership, late runs into the box, and scoring important goals."},
    {"id": "p12", "text": "Kylian Mbappe is one of the fastest and most dangerous forwards in football. He is known for explosive acceleration, direct dribbling, elite finishing, and his ability to attack space behind defenses."},
    {"id": "p13", "text": "Lionel Messi is widely regarded as one of the greatest footballers of all time. He is known for dribbling, vision, passing, free kicks, finishing, and his long career of success with Barcelona, Argentina, and Inter Miami."},
    {"id": "p14", "text": "Cristiano Ronaldo is one of football's greatest goalscorers. He is known for athleticism, heading, finishing, movement, mentality, and success with Manchester United, Real Madrid, Juventus, Portugal, and Al Nassr."},
    {"id": "p15", "text": "Neymar is a Brazilian forward known for flair, dribbling, creativity, close control, and one-versus-one ability. He starred for Santos, Barcelona, Paris Saint-Germain, Brazil, and later Al Hilal."},
    {"id": "p16", "text": "Luka Modric is a Croatian midfielder known for technical elegance, press resistance, passing, and game intelligence. He has been central to Real Madrid's Champions League success and won the Ballon d'Or in 2018."},
    {"id": "p17", "text": "Toni Kroos was a German midfielder known for passing accuracy, tempo control, set pieces, and composure under pressure. He played a major role in Real Madrid and Germany's success."},
    {"id": "p18", "text": "Sergio Ramos is a Spanish defender known for leadership, aggressive defending, aerial ability, and scoring important goals. He was a key figure for Real Madrid and Spain."},
    {"id": "p19", "text": "Karim Benzema is a French striker known for link-up play, movement, finishing, and intelligence. He became Real Madrid's main attacking leader after Cristiano Ronaldo left and won the Ballon d'Or in 2022."},
    {"id": "p20", "text": "Robert Lewandowski is one of the best strikers of his generation. He is known for clinical finishing, positioning, heading, and consistency, especially during his time at Borussia Dortmund, Bayern Munich, and Barcelona."},
    {"id": "p21", "text": "Vinicius Junior is a Brazilian winger for Real Madrid known for speed, dribbling, directness, and improved finishing. He is especially dangerous in transition and one-on-one situations."},
    {"id": "p22", "text": "Pedri is a Spanish midfielder for Barcelona known for intelligence, close control, passing, and calmness under pressure. He is often compared to classic Barcelona midfielders because of his technical style."},
    {"id": "p23", "text": "Gavi is a Spanish midfielder for Barcelona known for intensity, pressing, aggression, and technical quality. Despite his young age, he plays with high energy and maturity."},
    {"id": "p24", "text": "Declan Rice is an English midfielder known for ball-winning, defensive positioning, carrying the ball forward, and leadership. He became a key player for Arsenal after joining from West Ham."},
    {"id": "p25", "text": "Bruno Fernandes is Manchester United's creative midfielder known for chance creation, risk-taking passes, pressing, penalties, and long-range shooting."},
    {"id": "p26", "text": "Marcus Rashford is a Manchester United forward known for pace, direct running, shooting power, and attacking transitions. He is most dangerous when driving into space from the left."},
    {"id": "p27", "text": "Son Heung-min is a Tottenham Hotspur forward known for two-footed finishing, speed, movement, and counter-attacking threat. He has been one of the Premier League's most consistent attackers."},
    {"id": "p28", "text": "Cole Palmer developed into one of Chelsea's most important attacking players after leaving Manchester City. He is known for composure, creativity, penalties, dribbling, and decision-making in the final third."},
    {"id": "p29", "text": "Trent Alexander-Arnold is a Liverpool fullback known for elite passing, crossing, long balls, and chance creation from deep areas. He has also been used in an inverted midfield role."},
    {"id": "p30", "text": "Andrew Robertson is a Liverpool left-back known for stamina, overlapping runs, crossing, pressing, and defensive intensity. He formed one of the Premier League's best fullback pairs with Trent Alexander-Arnold."},
    {"id": "p31", "text": "Ruben Dias is a Manchester City centre-back known for leadership, defensive positioning, physicality, and organization. His arrival helped improve City's defensive stability."},
    {"id": "p32", "text": "William Saliba is an Arsenal centre-back known for composure, pace, strength, and calm defending. He has become one of the Premier League's best young defenders."},
    {"id": "p33", "text": "Gabriel Martinelli is an Arsenal winger known for speed, pressing, direct dribbling, and runs behind the defense. He is most dangerous when attacking from the left side."},
    {"id": "p34", "text": "Darwin Nunez is a Liverpool forward known for speed, physical power, chaotic movement, and high shot volume. He can play centrally or from the left."},
    {"id": "p35", "text": "Luis Diaz is a Liverpool winger known for dribbling, flair, work rate, and direct attacking play. He usually plays from the left and looks to beat defenders one versus one."},

    # --- TEAMS ---
    {"id": "tm1", "text": "Manchester City under Pep Guardiola play a possession-based style with high defensive line, inverted wingers, and a false nine or striker. They press aggressively and recycle possession quickly. They have dominated the Premier League winning multiple consecutive titles."},
    {"id": "tm2", "text": "Liverpool under Jurgen Klopp became one of Europe's best teams through gegenpressing, direct vertical passing, and dynamic attacking play. Their front three of Salah, Mane, and Firmino was one of the most feared in world football. Klopp left in 2024."},
    {"id": "tm3", "text": "Arsenal under Mikel Arteta play an aggressive high press with quick combinations in tight spaces. They have challenged for the Premier League title in recent seasons after years of rebuilding. Their style emphasizes positional play and pressing triggers."},
    {"id": "tm4", "text": "Chelsea have undergone significant rebuilding under new ownership with massive investment in players. They have struggled for consistency despite spending heavily. Under various managers they have experimented with different systems."},
    {"id": "tm5", "text": "Tottenham Hotspur have historically been known for attractive attacking football. Under Antonio Conte they adopted a more pragmatic 3-4-3 system. After Conte's departure they have continued searching for a consistent identity."},
    {"id": "tm6", "text": "Newcastle United have been transformed since their Saudi-led takeover in 2021. Under Eddie Howe they play an energetic pressing style and have qualified for European football for the first time in decades, investing heavily in the squad."},
    {"id": "tm7", "text": "Aston Villa under Unai Emery have become one of the Premier League's most improved sides. Emery's tactical organization and squad development have taken Villa from relegation candidates to European contenders within two seasons."},
    {"id": "tm8", "text": "Real Madrid are one of the most successful clubs in football history, especially in the UEFA Champions League. They are known for elite mentality, world-class players, fast transitions, and the ability to win decisive knockout matches."},
    {"id": "tm9", "text": "Barcelona are famous for La Masia, possession football, and technical midfielders. Their modern identity was shaped by Johan Cruyff and later perfected under Pep Guardiola with players like Messi, Xavi, Iniesta, and Busquets."},
    {"id": "tm10", "text": "Bayern Munich are Germany's dominant club and are known for attacking football, strong physical players, and consistent success in the Bundesliga. They have also won multiple Champions League titles."},
    {"id": "tm11", "text": "Paris Saint-Germain became a European superclub after major investment from Qatar Sports Investments. They have dominated French football and attracted global stars such as Neymar, Mbappe, Messi, and Ibrahimovic."},
    {"id": "tm12", "text": "Borussia Dortmund are known for passionate fans, the Yellow Wall, attacking football, and developing young players. They have produced or developed stars such as Lewandowski, Haaland, Bellingham, and Sancho."},
    {"id": "tm13", "text": "Atletico Madrid under Diego Simeone became famous for defensive discipline, compact shape, counter-attacks, and emotional intensity. They have challenged Barcelona and Real Madrid despite smaller resources."},
    {"id": "tm14", "text": "Inter Milan are one of Italy's biggest clubs and have a history of strong defensive teams, tactical discipline, and success in Serie A and European competitions."},
    {"id": "tm15", "text": "AC Milan are one of Europe's most historic clubs, known for legendary defenders, midfielders, and Champions League success. The club has had iconic players such as Maldini, Kaka, Pirlo, and Shevchenko."},
    {"id": "tm16", "text": "Juventus are Italy's most successful domestic club, known for defensive organization, winning mentality, and long periods of Serie A dominance."},
    {"id": "tm17", "text": "Napoli became famous for attacking football and passionate support, especially during the Diego Maradona era and later during their Serie A title-winning campaign with players like Victor Osimhen and Khvicha Kvaratskhelia."},
    {"id": "tm18", "text": "Manchester United are one of the biggest clubs in world football. Their most successful period came under Sir Alex Ferguson, when they dominated English football and won multiple Premier League titles and Champions League trophies."},
    {"id": "tm19", "text": "West Ham United are known for their academy tradition, physical style, and passionate East London fanbase. They won the UEFA Europa Conference League in 2023."},
    {"id": "tm20", "text": "Brighton & Hove Albion became admired for smart recruitment, possession football, and developing undervalued players. Their data-driven model has helped them compete with richer Premier League clubs."},
    {"id": "tm21", "text": "Brentford are known for analytics-based recruitment, set-piece strength, and efficient squad building. They reached the Premier League with a modern data-focused approach."},
    {"id": "tm22", "text": "Leicester City shocked world football by winning the Premier League in 2015-16. Their title-winning team relied on compact defending, quick counter-attacks, Jamie Vardy's pace, and Riyad Mahrez's creativity."},

    # --- RULES ---
    {"id": "r1", "text": "The offside rule states a player is offside if they are nearer to the opponent's goal than both the ball and the second-to-last defender when the ball is played to them. Being offside is only an offense if the player is involved in active play."},
    {"id": "r2", "text": "VAR (Video Assistant Referee) was introduced to the Premier League in 2019. It reviews clear and obvious errors in four categories: goals, penalty decisions, direct red cards, and mistaken identity. The on-field referee can be advised to review incidents on a pitchside monitor."},
    {"id": "r3", "text": "A penalty kick is awarded when a foul or handball occurs inside the penalty area. It is taken from the penalty spot 12 yards from goal. All players except the taker and goalkeeper must be outside the penalty area until the ball is kicked."},
    {"id": "r4", "text": "The handball rule states that it is an offense if a player deliberately handles the ball. Goals scored with the hand or arm are disallowed. Unintentional handball can still be penalized if it leads directly to a goal or goal-scoring opportunity."},
    {"id": "r5", "text": "A red card results in immediate dismissal from the match. A player receives a red card for violent conduct, serious foul play, spitting, denying a clear goal-scoring opportunity, or receiving two yellow cards in the same match. The team plays with ten men for the remainder of the game."},
    {"id": "r6", "text": "A yellow card is a caution given by the referee for misconduct such as reckless tackles, dissent, time wasting, or stopping a promising attack. Two yellow cards in the same match result in a red card."},
    {"id": "r7", "text": "Added time is extra time added at the end of each half to compensate for stoppages such as injuries, substitutions, VAR checks, goal celebrations, and time wasting."},
    {"id": "r8", "text": "A free kick is awarded after a foul or rule violation. Direct free kicks can be shot straight into the goal, while indirect free kicks must touch another player before a goal can count."},
    {"id": "r9", "text": "A corner kick is awarded when the defending team last touches the ball before it crosses their own goal line without a goal being scored. Corners are important attacking set-piece opportunities."},
    {"id": "r10", "text": "A goal kick is awarded when the attacking team last touches the ball before it crosses the defending team's goal line without a goal being scored. The defending team restarts play from inside the goal area."},
    {"id": "r11", "text": "A throw-in is awarded when the ball fully crosses the touchline. The player taking the throw must use both hands, throw from behind and over the head, and keep both feet on or behind the touchline."},
    {"id": "r12", "text": "A foul is an unfair action such as tripping, pushing, holding, charging recklessly, or kicking an opponent. Fouls can result in free kicks, penalties, yellow cards, or red cards depending on severity and location."},
    {"id": "r13", "text": "Advantage is when the referee allows play to continue after a foul because the fouled team still has a promising attacking situation. If the advantage does not develop, the referee may bring play back."},
    {"id": "r14", "text": "A substitution allows a team to replace one player with another during a match. Modern competitions usually allow five substitutions, though the exact number can depend on the competition rules."},
    {"id": "r15", "text": "A player is considered in active play for offside if they interfere with play, interfere with an opponent, or gain an advantage from their position. Simply standing in an offside position is not automatically an offense."},
    {"id": "r16", "text": "Denial of an obvious goal-scoring opportunity, often called DOGSO, can result in a red card if a player illegally prevents an opponent from having a clear chance to score."},
    {"id": "r17", "text": "Serious foul play involves a challenge that endangers the safety of an opponent. It is usually punished with a red card."},
    {"id": "r18", "text": "Violent conduct refers to aggressive behavior away from a legitimate attempt to play the ball, such as striking or elbowing an opponent. It is punished with a red card."},
    {"id": "r19", "text": "The captain has no special rule-making power but is often the main player who communicates with the referee. Captains lead teammates, organize behavior, and represent the team during key moments."},
    {"id": "r20", "text": "The goalkeeper is the only player allowed to handle the ball, but only inside their own penalty area. Outside the box, the goalkeeper is treated like any other outfield player."},
    
    
    # --- COMPETITIONS ---
    {"id": "c1", "text": "The Premier League was founded in 1992 when the top clubs broke away from the Football League. It consists of 20 clubs playing 38 matches each season. Manchester United have won it the most times with 13 titles since its formation. It is the most watched football league in the world."},
    {"id": "c2", "text": "The UEFA Champions League is Europe's premier club competition. It features the top clubs from each European league competing in a group stage followed by knockout rounds. The final is one of the most watched sporting events globally."},
    {"id": "c3", "text": "The FA Cup is the oldest football competition in the world, founded in 1871. It is a knockout tournament open to all clubs in the English football pyramid. It is known for potential giant-killing upsets where lower league clubs defeat top flight teams."},
    {"id": "c4", "text": "La Liga is Spain's top football division and has historically been dominated by Real Madrid and Barcelona. It is known for technical football, elite midfielders, and world-class attacking players."},
    {"id": "c5", "text": "Serie A is Italy's top football league and is known for tactical sophistication, defensive organization, and historic clubs such as Juventus, Inter Milan, AC Milan, Roma, Lazio, and Napoli."},
    {"id": "c6", "text": "The Bundesliga is Germany's top football league and is known for high attendances, intense pressing, attacking football, and strong fan culture. Bayern Munich have dominated the competition for long periods."},
    {"id": "c7", "text": "Ligue 1 is France's top football division. It has produced many talented young players and has been dominated in recent years by Paris Saint-Germain."},
    {"id": "c8", "text": "The UEFA Europa League is Europe's second-tier club competition. It features strong clubs from across Europe and often provides a route into the Champions League for the winner."},
    {"id": "c9", "text": "The UEFA Europa Conference League is Europe's third-tier club competition. It gives more clubs from smaller leagues the chance to compete in European knockout football."},
    {"id": "c10", "text": "The FIFA World Cup is the biggest international football tournament. It is held every four years and features national teams from around the world competing for the most prestigious trophy in football."},
    {"id": "c11", "text": "The UEFA European Championship, also called the Euros, is the main international tournament for European national teams. It is held every four years and features many of the world's strongest football nations."},
    {"id": "c12", "text": "Copa America is South America's main international football competition. It includes countries such as Brazil, Argentina, Uruguay, Chile, Colombia, and Peru."},
    {"id": "c13", "text": "The Africa Cup of Nations, also called AFCON, is Africa's main international football tournament. It showcases top African national teams and players from leagues across the world."},
    {"id": "c14", "text": "The Carabao Cup, also known as the EFL Cup, is a domestic knockout competition in English football. It includes clubs from the Premier League and the English Football League."},
    {"id": "c15", "text": "The Community Shield is an annual English match usually played between the Premier League champion and the FA Cup winner. It traditionally acts as the curtain-raiser for the English football season."},
    {"id": "c16", "text": "The Copa del Rey is Spain's main domestic cup competition. It gives clubs from different levels of Spanish football the chance to compete in a knockout format."},
    {"id": "c17", "text": "The DFB-Pokal is Germany's main domestic cup competition. It is known for knockout drama and occasional upsets by lower-division teams."},
    {"id": "c18", "text": "The Coppa Italia is Italy's main domestic cup competition. Serie A clubs often enter in later rounds, and the winner earns domestic silverware and possible European qualification."},


    # --- MANAGERS ---
    {"id": "m1", "text": "Pep Guardiola is one of the most influential managers in modern football. His teams are known for positional play, possession dominance, pressing, tactical flexibility, and intelligent use of space."},
    {"id": "m2", "text": "Jurgen Klopp is known for gegenpressing, emotional leadership, high-intensity football, and building strong team culture. His Borussia Dortmund and Liverpool teams played fast, aggressive, vertical football."},
    {"id": "m3", "text": "Jose Mourinho is famous for pragmatic tactics, defensive structure, counter-attacking football, and winning major trophies with Porto, Chelsea, Inter Milan, Real Madrid, Manchester United, Roma, and other clubs."},
    {"id": "m4", "text": "Carlo Ancelotti is known for calm leadership, tactical adaptability, man-management, and success in the Champions League. He has managed elite clubs including AC Milan, Chelsea, PSG, Bayern Munich, Everton, and Real Madrid."},
    {"id": "m5", "text": "Mikel Arteta has transformed Arsenal with positional play, high pressing, structured build-up, and improved defensive organization. He previously worked as Pep Guardiola's assistant at Manchester City."},
    {"id": "m6", "text": "Diego Simeone is known for compact defending, emotional intensity, counter-attacking football, and making Atletico Madrid highly competitive against richer clubs."},
    {"id": "m7", "text": "Antonio Conte is known for back-three systems, intense training, wingback-focused attacks, and disciplined defensive organization. His teams often use formations such as 3-5-2 or 3-4-3."},
    {"id": "m8", "text": "Unai Emery is known for tactical preparation, European competition success, structured pressing, and improving clubs through detailed coaching. He has been especially successful in the Europa League."},
    {"id": "m9", "text": "Sir Alex Ferguson is the most successful manager in Manchester United's history. He was known for squad rebuilding, mentality, late goals, attacking football, and long-term dominance in English football."},
    {"id": "m10", "text": "Zinedine Zidane achieved major success as Real Madrid manager, winning three consecutive Champions League titles. He was known for calm leadership, man-management, and getting the best out of elite players."},

    # --- FOOTBALL CONCEPTS ---
    {"id": "fc1", "text": "Expected goals, or xG, is a statistic that estimates the quality of a chance based on factors like shot location, angle, body part, and type of assist. A higher xG means the chance was more likely to result in a goal."},
    {"id": "fc2", "text": "Expected assists, or xA, measures the likelihood that a pass will become an assist based on the quality of the chance created. It helps evaluate creative players beyond actual assist totals."},
    {"id": "fc3", "text": "Progressive passes are passes that move the ball significantly closer to the opponent's goal. They are useful for measuring players who advance play rather than simply keeping possession."},
    {"id": "fc4", "text": "Progressive carries are dribbles or ball carries that move the ball significantly closer to goal. They show how players break lines by running with the ball."},
    {"id": "fc5", "text": "Press resistance is a player's ability to keep the ball under pressure. Midfielders with good press resistance use body positioning, close control, and awareness to escape opponents."},
    {"id": "fc6", "text": "Line-breaking passes are passes that bypass one or more defensive lines. They are valuable because they move the ball into more dangerous areas and disrupt the opponent's structure."},
    {"id": "fc7", "text": "Chance creation refers to actions that lead to shots, such as key passes, crosses, through balls, cutbacks, and set-piece deliveries."},
    {"id": "fc8", "text": "A clean sheet means a team has prevented the opponent from scoring during a match. Goalkeepers and defenders are often judged partly by clean sheets."},
    {"id": "fc9", "text": "A brace means a player has scored two goals in a single match. A hat-trick means a player has scored three goals in one match."},
    {"id": "fc10", "text": "A derby is a match between rival teams, usually from the same city or region. Examples include the Manchester Derby, North London Derby, Merseyside Derby, and Madrid Derby."},
    {"id": "fc11", "text": "The number 10 role traditionally refers to a creative attacking midfielder who plays between midfield and attack. This player is responsible for chance creation, final passes, and linking play."},
    {"id": "fc12", "text": "The number 6 role usually refers to a defensive midfielder who protects the back line, wins the ball, and helps progress possession from deep areas."},
    {"id": "fc13", "text": "The number 8 role usually refers to a central midfielder who contributes to both attack and defense. Number 8s often press, carry the ball, combine with attackers, and make late runs."},
    {"id": "fc14", "text": "A through ball is a pass played into space behind the defensive line for an attacker to run onto. It is commonly used against high defensive lines."},
    {"id": "fc15", "text": "A cutback is a pass from near the byline back toward the penalty spot or edge of the box. Cutbacks are dangerous because defenders often run toward their own goal and attackers arrive facing goal."},
    {"id": "fc16", "text": "A high defensive line means defenders position themselves far up the pitch. It helps compress space and support pressing but can be vulnerable to fast attackers running in behind."},
    {"id": "fc17", "text": "A transition is the moment when possession changes from one team to the other. Attacking transitions happen after winning the ball, while defensive transitions happen after losing it."},
    {"id": "fc18", "text": "A second ball is the loose ball after an aerial duel, clearance, or tackle. Winning second balls is important for controlling territory and sustaining attacks."},
    {"id": "fc19", "text": "A duel is a contest between two players for the ball. Duels can be aerial, ground-based, physical, or technical."},
    {"id": "fc20", "text": "Ball retention means keeping possession under pressure. Teams with good ball retention can control matches, reduce defensive stress, and tire opponents."},


  # --- HISTORIC MOMENTS ---
    {"id": "h1", "text": "Leicester City's Premier League title win in 2015-16 is considered one of the greatest underdog stories in sports history. They started the season as relegation candidates but won the league with counter-attacking football and team unity."},
    {"id": "h2", "text": "Manchester United's 1999 Champions League final comeback against Bayern Munich is one of football's most famous moments. United scored twice in stoppage time to complete a historic treble-winning season."},
    {"id": "h3", "text": "Liverpool's comeback against Barcelona in the 2019 Champions League semi-final is known as one of Anfield's greatest nights. Liverpool overturned a 3-0 first-leg deficit by winning 4-0 at home."},
    {"id": "h4", "text": "Argentina won the 2022 FIFA World Cup after beating France in a dramatic final on penalties. Lionel Messi played a central role and finally won the biggest trophy in international football."},
    {"id": "h5", "text": "Spain dominated international football from 2008 to 2012, winning Euro 2008, the 2010 World Cup, and Euro 2012. Their success was built on possession football and midfield control."},
    {"id": "h6", "text": "Barcelona's 2009 team under Pep Guardiola won the treble with a style based on pressing, possession, and technical superiority. The team included Messi, Xavi, Iniesta, Busquets, Puyol, and Dani Alves."},
    {"id": "h7", "text": "Real Madrid won three consecutive Champions League titles from 2016 to 2018 under Zinedine Zidane. Cristiano Ronaldo, Sergio Ramos, Luka Modric, Toni Kroos, and Karim Benzema were key players."},
    {"id": "h8", "text": "Arsenal's 2003-04 Invincibles went unbeaten for an entire Premier League season. Managed by Arsene Wenger, the team included Thierry Henry, Patrick Vieira, Dennis Bergkamp, Robert Pires, and Sol Campbell."},
    {"id": "h9", "text": "Germany defeated Brazil 7-1 in the 2014 World Cup semi-final. The match became one of the most shocking results in World Cup history."},
    {"id": "h10", "text": "Sergio Aguero's last-minute goal against QPR in 2012 won Manchester City their first Premier League title. The moment is remembered as one of the most dramatic finishes in English football history."},


   # --- NATIONAL TEAMS ---
    {"id": "nt1", "text": "Brazil are the most successful national team in World Cup history, known for technical skill, attacking flair, and legendary players such as Pele, Ronaldo, Ronaldinho, Rivaldo, Neymar, and Romario."},
    {"id": "nt2", "text": "Argentina are one of football's greatest national teams, with legendary players such as Diego Maradona and Lionel Messi. They won the World Cup in 1978, 1986, and 2022."},
    {"id": "nt3", "text": "Germany are known for tournament mentality, physical strength, tactical discipline, and consistency. They have won multiple World Cups and European Championships."},
    {"id": "nt4", "text": "France have produced many world-class players and won the World Cup in 1998 and 2018. Their modern teams are known for athleticism, technical quality, and squad depth."},
    {"id": "nt5", "text": "England invented modern football and have one World Cup title from 1966. The national team has often had talented players but has faced pressure and expectation in major tournaments."},
    {"id": "nt6", "text": "Spain became a dominant national team between 2008 and 2012, using possession football and technical midfielders to win three major tournaments in a row."},
    {"id": "nt7", "text": "Italy are famous for defensive organization, tactical intelligence, and major tournament success. They have won multiple World Cups and European Championships."},
    {"id": "nt8", "text": "Portugal have produced great players such as Eusebio, Luis Figo, and Cristiano Ronaldo. They won Euro 2016 and the 2019 UEFA Nations League."},
    {"id": "nt9", "text": "Netherlands are known for Total Football, technical players, and attacking ideas. Although they have reached several World Cup finals, they have not won the tournament."},
    {"id": "nt10", "text": "Morocco became the first African team to reach a World Cup semi-final in 2022. Their success was built on defensive organization, discipline, and strong team spirit."},

    # --- STADIUMS AND FAN CULTURE ---
    {"id": "s1", "text": "Anfield is Liverpool's home stadium and is famous for its atmosphere, especially on European nights. The Kop stand and the anthem You'll Never Walk Alone are central to Liverpool's identity."},
    {"id": "s2", "text": "Old Trafford is Manchester United's home stadium and is nicknamed the Theatre of Dreams. It is one of the most famous football stadiums in the world."},
    {"id": "s3", "text": "Camp Nou is Barcelona's historic home stadium and one of the largest football stadiums in Europe. It has hosted many iconic matches and legendary players."},
    {"id": "s4", "text": "Santiago Bernabeu is Real Madrid's home stadium and one of football's most iconic venues. It has hosted Champions League finals, World Cup matches, and many historic European nights."},
    {"id": "s5", "text": "Signal Iduna Park is Borussia Dortmund's home stadium and is famous for the Yellow Wall, one of the most intense and passionate fan stands in world football."},
    {"id": "s6", "text": "Wembley Stadium is England's national stadium and hosts FA Cup finals, League Cup finals, England matches, and major international fixtures."},
    {"id": "s7", "text": "The San Siro in Milan is shared by AC Milan and Inter Milan. It is one of Europe's most historic stadiums and has hosted many major domestic and European matches."},
    {"id": "s8", "text": "The Emirates Stadium is Arsenal's home ground. Arsenal moved there from Highbury in 2006 to increase capacity and modernize the club's facilities."},
    {"id": "s9", "text": "St James' Park is Newcastle United's home stadium and is known for passionate support and a central location in the city of Newcastle."},
    {"id": "s10", "text": "Tottenham Hotspur Stadium is one of the most modern football stadiums in the world. It hosts football matches, NFL games, concerts, and other major events."},

]

add_documents(docs)
print(f"Vector store seeded with {len(docs)} documents.")